# Generated by Django 2.2.3 on 2019-07-27 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_position_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.CharField(choices=[('Food', 'Еда'), ('Alcohool', 'Бухло'), ('Rent', 'Аренда'), ('House', 'Быт'), ('Hobby', 'Хобби'), ('Education', 'Развитие')], default='Food', max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
